//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelibateMusicAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C7602Sale
    {
        public System.DateTime SaleDate { get; set; }
        public int PricePaid { get; set; }
        public string RecordID { get; set; }
        public int CustomerNumber { get; set; }
        public string InterestCode { get; set; }
    
        public virtual C7602Customer C7602Customer { get; set; }
        public virtual C7602Record C7602Record { get; set; }
    }
}
