//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelibateMusicAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DADEntities : DbContext
    {
        public DADEntities()
            : base("name=DADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C7602Customer> C7602Customer { get; set; }
        public virtual DbSet<C7602Interest> C7602Interest { get; set; }
        public virtual DbSet<C7602Record> C7602Record { get; set; }
        public virtual DbSet<C7602Sale> C7602Sale { get; set; }
    }
}
